package visual;

import dao_tabela_atributos.DaoViagens;
import java.sql.SQLException;
import javax.swing.Timer;
import tabela_atributos.Viagem;

public class JDialogViagem extends javax.swing.JDialog {

    private boolean isAlter = false;
    private int alterId;  
    
    /**
     * Creates new form JFrameTeste
     */
    public JDialogViagem() {
        setModal(true);
        initComponents();
    }
    
    public JDialogViagem(boolean isAlter, Viagem v) {
        setModal(true);
        initComponents();
        if (isAlter) {
            this.isAlter = true;
            localOrigem.setText(String.valueOf(v.getLocalDeOrigem()));
            localDestino.setText(String.valueOf(v.getLocalDeDestino()));
            Motorista.setText(String.valueOf(v.getId_Motorista()));
            Veiculo.setText(v.getId_Veiculo());
            Evento.setText(String.valueOf(v.getId_Evento()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        localOrigem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        localDestino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Motorista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Veiculo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();
        erro = new javax.swing.JLabel();
        Evento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        escolherOrigem = new javax.swing.JButton();
        escolherDestino = new javax.swing.JButton();
        escolherMotorista = new javax.swing.JButton();
        escolherVeiculo = new javax.swing.JButton();
        escolherEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Local origem");

        jLabel3.setText("Local de destino");

        jLabel4.setText("Motorista");

        jLabel5.setText("Veiculo");

        mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagem.setText("Insira o cadastro do carro, por favor");

        erro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erro.setMaximumSize(new java.awt.Dimension(187, 16));
        erro.setMinimumSize(new java.awt.Dimension(187, 16));
        erro.setPreferredSize(new java.awt.Dimension(187, 16));

        jLabel6.setText("Evento");

        escolherOrigem.setText("<html>Escolher<br>Origem\n");
        escolherOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherOrigemActionPerformed(evt);
            }
        });

        escolherDestino.setText("<html>Escolher<br>Destino");
        escolherDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherDestinoActionPerformed(evt);
            }
        });

        escolherMotorista.setText("<html>Escolher<br>Motorista\n");
        escolherMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherMotoristaActionPerformed(evt);
            }
        });

        escolherVeiculo.setText("<html>Escolher<br>Veiculo");
        escolherVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherVeiculoActionPerformed(evt);
            }
        });

        escolherEvento.setText("<html>Escolher<br>Evento");
        escolherEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addComponent(erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(escolherOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(escolherDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(escolherMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Motorista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(escolherVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(escolherEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Evento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Motorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escolherOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escolherDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escolherMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escolherVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escolherEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(8, 8, 8)
                .addComponent(mensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(erro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Viagem v = new Viagem();

        try {
            v.setLocalDeOrigem(Integer.parseInt(localOrigem.getText()));
            v.setLocalDeDestino(Integer.parseInt(localDestino.getText()));
            v.setId_Motorista(Integer.parseInt(Motorista.getText()));
            v.setId_Veiculo(Veiculo.getText());
            v.setId_Evento(Integer.parseInt(Evento.getText()));
            v.setId(alterId);
        } catch (NumberFormatException e) {
            erro.setText("numero?");
            return;
        }

        DaoViagens dao = new DaoViagens();

        try {
            mensagem.setText("Inserindo no banco...");
            if (isAlter) {
                dao.alterarDados(v);
            } else {
                dao.InserirDados(v);
            }
            
            mensagem.setText("Viagem cadastrada com sucesso!");
            erro.setText("");

            jButton1.setEnabled(false);

            new Timer(5000, x -> dispose()) {{
                setRepeats(false);
                start();
            }};

        } catch (SQLException ex) {
            mensagem.setText("Erro ao inserir no banco!");
            erro.setText(ex.getMessage());
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void escolherOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherOrigemActionPerformed
        JDialogEscolha consulta = new JDialogEscolha(0); // 0 de Enderecos
        consulta.setVisible(true);
        localOrigem.setText(consulta.id);
    }//GEN-LAST:event_escolherOrigemActionPerformed

    private void escolherDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherDestinoActionPerformed
        JDialogEscolha consulta = new JDialogEscolha(0); // 0 de Enderecos
        consulta.setVisible(true);
        localDestino.setText(consulta.id);
    }//GEN-LAST:event_escolherDestinoActionPerformed

    private void escolherMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherMotoristaActionPerformed
        JDialogEscolha consulta = new JDialogEscolha(2); // 2 de Motorista
        consulta.setVisible(true);
        Motorista.setText(consulta.id);
    }//GEN-LAST:event_escolherMotoristaActionPerformed

    private void escolherVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherVeiculoActionPerformed
        JDialogEscolha consulta = new JDialogEscolha(4); // 4 de Veiculo
        consulta.setVisible(true);
        Veiculo.setText(consulta.id);
    }//GEN-LAST:event_escolherVeiculoActionPerformed

    private void escolherEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherEventoActionPerformed
        JDialogEscolha consulta = new JDialogEscolha(1); // 1 de Evento
        consulta.setVisible(true);
        Evento.setText(consulta.id);
    }//GEN-LAST:event_escolherEventoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Evento;
    private javax.swing.JTextField Motorista;
    private javax.swing.JTextField Veiculo;
    private javax.swing.JLabel erro;
    private javax.swing.JButton escolherDestino;
    private javax.swing.JButton escolherEvento;
    private javax.swing.JButton escolherMotorista;
    private javax.swing.JButton escolherOrigem;
    private javax.swing.JButton escolherVeiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField localDestino;
    private javax.swing.JTextField localOrigem;
    private javax.swing.JLabel mensagem;
    // End of variables declaration//GEN-END:variables
}
