package visual;

import dao_tabela_atributos.*;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import tabela_atributos.*;
import util.TableHelper;

public class JDialogEscolha extends javax.swing.JDialog {

    public String id = "";
    private int entidadeIndex;
    private int idIndex;
    
    /**
     * Creates new form JFrameTabela
     */
    public JDialogEscolha(int entidade) {
        setModal(true);
        initComponents();
        this.entidadeIndex = entidade;
        
        ResultSet rs = null;
        switch (this.entidadeIndex) {
            case 0:
                DaoEnderecos den = new DaoEnderecos();
                rs = den.getResultSet();
                this.idIndex = den.idIndex;
                break;
            case 1:
                DaoEventos dev = new DaoEventos();
                rs = dev.getResultSet();
                this.idIndex = dev.idIndex;
                break;
            case 2:
                DaoMotoristas dm = new DaoMotoristas();
                rs = dm.getResultSet();
                this.idIndex = dm.idIndex;
                break;
            case 3:
                DaoPassageiros dp = new DaoPassageiros();
                rs = dp.getResultSet();
                this.idIndex = dp.idIndex;
                break;                
            case 4:
                DaoVeiculos dv = new DaoVeiculos();
                rs = dv.getResultSet();
                this.idIndex = dv.idIndex;
                break;
            case 5:
                DaoViagens dvi = new DaoViagens();
                rs = dvi.getResultSet();
                this.idIndex = dvi.idIndex;
                break;
        }
        DefaultTableModel model = TableHelper.modelFromRS(rs);
        tabela.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        escolher = new javax.swing.JButton();

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.setToolTipText("");
        jScrollPane1.setViewportView(tabela);

        escolher.setText("Escolher Dado Selecionado");
        escolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(escolher)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escolher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherActionPerformed
        this.id = "";
        
        if (tabela.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum dado selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.id = String.valueOf(tabela.getModel().getValueAt(tabela.getSelectedRow(), this.idIndex - 1));
            
        dispose();
    }//GEN-LAST:event_escolherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton escolher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
