package visual;

import dao_tabela_atributos.*;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import util.SQLHelper;
import util.TableHelper;

public class JFrameTabela extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTabela
     */
    public JFrameTabela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        remover = new javax.swing.JButton();
        SelecaoTabela = new javax.swing.JComboBox<>();
        alterar = new javax.swing.JButton();
        inserir = new javax.swing.JButton();
        consulta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.setToolTipText("");
        jScrollPane1.setViewportView(tabela);

        remover.setText("Remover Dados Selecionados");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        SelecaoTabela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Endereços", "Eventos", "Motoristas", "Passageiros", "Veiculos", "Viagens" }));
        SelecaoTabela.setSelectedIndex(-1);
        SelecaoTabela.setToolTipText("");
        SelecaoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoTabelaActionPerformed(evt);
            }
        });

        alterar.setText("Alterar Dados Selecionados");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        inserir.setText("Inserir Dados na Tabela Selecionada");
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });

        consulta.setPreferredSize(new java.awt.Dimension(95, 22));
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        jLabel1.setText("Consultar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SelecaoTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inserir)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta, 0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(SelecaoTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remover)
                    .addComponent(alterar)
                    .addComponent(inserir)
                    .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelecaoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoTabelaActionPerformed
        ResultSet rs = null;
        switch (SelecaoTabela.getSelectedIndex()) {
            case 0:
                DaoEnderecos den = new DaoEnderecos();
                rs = den.getResultSet();
                break;
            case 1:
                DaoEventos dev = new DaoEventos();
                rs = dev.getResultSet();
                break;
            case 2:
                DaoMotoristas dm = new DaoMotoristas();
                rs = dm.getResultSet();
                break;
            case 3:
                DaoPassageiros dp = new DaoPassageiros();
                rs = dp.getResultSet();
                break;                
            case 4:
                DaoVeiculos dv = new DaoVeiculos();
                rs = dv.getResultSet();
                break;
            case 5:
                DaoViagens dvi = new DaoViagens();
                rs = dvi.getResultSet();
                break;
        }
        DefaultTableModel model = TableHelper.modelFromRS(rs);
        tabela.setModel(model);
        
        
        // Criar um listener para ver quando uma celula é mudada
        model.addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                // Check for update type
                if (e.getType() == TableModelEvent.UPDATE) {
                    int row = e.getFirstRow();
                    int column = e.getColumn();
                    Object data = model.getValueAt(row, column);
                    System.out.println("Updated value at row " + row + ", column " + column + ": " + data);
                }
            }
        });
    }//GEN-LAST:event_SelecaoTabelaActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        DaoEventos dev = new DaoEventos();
        DaoViagens dvi = new DaoViagens();
        DaoMotoristas dm = new DaoMotoristas();
        DaoVeiculos dv = new DaoVeiculos();
        DaoPassageiros dp = new DaoPassageiros();
        DaoEnderecos de = new DaoEnderecos();
        
        String[] ids = new String[tabela.getSelectedRowCount()];
        int indexids = 0;
        
        // O(n²) - duas for nested
        for (int y : tabela.getSelectedRows()) {
            for (int x = 0; x < tabela.getColumnCount(); x++) {
                //System.out.println("x: " + x + " y: " + y + " " + tabela.getColumnName(x));
                if (tabela.getColumnName(x).startsWith("id_")) {
                    String into;
                    try {
                        into = (String)tabela.getModel().getValueAt(y, x);
                    } catch (ClassCastException ex) {
                        into = String.valueOf(tabela.getModel().getValueAt(y, x));
                    }
                    ids[indexids] = into;
                    indexids++;
                }
            }
        }
        
        if (ids.length == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum dado selecionado", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            switch (SelecaoTabela.getSelectedIndex()) {
                case 0:
                    //Endereços
                    de.checkDependencias(ids);
                    break;
                case 1:
                    //Eventos
                    break;
                case 2:
                    //Motoristas
                    break;
               case 3:
                   //Passageiros
                     break;                
                case 4:
                    //Veiculos
                    break;
                case 5:
                    //Viagens
                    break;
                default:
                    DaoViagens dvi2 = new DaoViagens();
                    break;
            }
        } catch (Exception ex) {
            return;
        }
        
        
        int confirmacao = JOptionPane.showConfirmDialog(this, "Certeza que quer apagar os dados com ids:\n" + Arrays.toString(ids), "Confirmação", JOptionPane.ERROR_MESSAGE);
        if (confirmacao == JOptionPane.YES_OPTION) {
            ResultSet rs;
            for (String id : ids) {
            switch (SelecaoTabela.getSelectedIndex()) {
                case 0:
                    DaoEnderecos den = new DaoEnderecos();
                    den.removeByID(Integer.parseInt(id));
                    rs = den.getResultSet();
                    break;
                case 1:
                    dev.removeByID(Integer.parseInt(id));
                    rs = dev.getResultSet();
                    break;
                case 2:
                    dm.removeByID(Integer.parseInt(id));
                    rs = dm.getResultSet();
                    break;
                case 3:
                    dp.removeByID(Integer.parseInt(id));
                    rs = dp.getResultSet();
                    break;                
                case 4:
                    dv.removeByID(id);
                    rs = dv.getResultSet();
                    break;
                case 5:
                    dvi.removeByID(Integer.parseInt(id));
                    rs = dvi.getResultSet();
                    break;
                default:
                    DaoViagens dvi2 = new DaoViagens();
                    dvi2.removeByID(Integer.parseInt(id));
                    rs = dvi2.getResultSet();
                    break;
                }
                tabela.setModel(TableHelper.modelFromRS(rs));
            }
        }
    }//GEN-LAST:event_removerActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO Adicionar código de alteração
        // Pegar as linhas selecionadas, pegar os dados DA TABELA DA GUI de cada uma e atualizar elas no banco de dados
    }//GEN-LAST:event_alterarActionPerformed

    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed
        // TODO Criar tela de Inserção de dados, criar uma para cada tabela.
        switch (SelecaoTabela.getSelectedIndex()) {
            case 0:
                JDialog endereco = new JDialogEndereco();
                endereco.setVisible(true);
                break;
            case 1:
                JDialog evento = new JDialogEvento();
                evento.setVisible(true);
                break;
            case 2:
                JDialog motoristas = new JDialogMotorista();
                motoristas.setVisible(true);
                break;
            case 3:
                JDialogPassageiro passageiro = new JDialogPassageiro();
                passageiro.setVisible(true);
                break;                
            case 4:
                JDialogVeiculo veiculo = new JDialogVeiculo();
                veiculo.setVisible(true);
                break;
            case 5:
                JDialogViagem viagem = new JDialogViagem();
                viagem.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Nenhuma tabela selecionada", "Erro", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }//GEN-LAST:event_inserirActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO Colocar consulta de foreign keys dependendo da tabela e linha selecionada
        // usar consulta.getSelectedItem()
    }//GEN-LAST:event_consultaActionPerformed

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelecaoTabela;
    private javax.swing.JButton alterar;
    private javax.swing.JComboBox<String> consulta;
    private javax.swing.JButton inserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remover;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
